[package]
name = "mpd-notification-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.8.0"
mpd = "0.0.12" #{ git = "https://github.com/kstep/rust-mpd.git" }
time = "*"